name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install
      run: |
        sudo sh -c "wget -O - https://dl.openfoam.org/gpg.key | apt-key add -"
        sudo add-apt-repository http://dl.openfoam.org/ubuntu
        sudo apt install openfoam8
    - name: test
      run: make tester

